Sequence InvariantMonoidals
typelevel/kittens pull request #246
Opened 2020-08-22 18:39 UTC by vinayakpathak

I don't think we need `F[_]` to be an `Applicative` to be able to sequence over it. `InvariantMonoidal` is all we need.

2020-08-24 14:57 UTC, vinayakpathak commented
Yes, ok, I wasn't sure how to take care of the binary incompatibility. I'll try what you suggest and update

2020-09-05 17:10 UTC, vinayakpathak commented
Ok, I've updated it. Seems like it's binary compatible now. I also added a few tests to test just the `InvariantMonoidal` part.

I'm not 100% sure that the way I've split things into different priorities is right. Please let me know if I've messed something up.

2020-10-22 23:32 UTC, joroKr21 requested changes
Thanks for the contribution! This is really complex stuff, but the use case with `Semigroup` looks really nice (although we already have derivation for that particular type class). The inheritance relation between `MkHNilSequencerLowPrio` and `MkHConsSequencerLowPrio` also has to be inverted.

2020-10-22 23:32 UTC, joroKr21 commented on core/src/main/scala/cats/sequence/sequence.scala
> +                                                                                implicit tailSequencer: Aux[FT, F0, T], F: InvariantMonoidal[F0]
```suggestion
                                                                                implicit tailSequencer: Aux[FT, F0, T], F: InvariantSemigroupal[F0]
```

2020-10-22 23:32 UTC, joroKr21 commented on core/src/main/scala/cats/sequence/sequence.scala
> +trait MkHNilSequencerLowPrio {
This is to ensure we can evolve it later while preserving binary compatibility:
```suggestion
private[sequence] abstract class MkHNilSequencerLowPrio {
```

2020-10-22 23:32 UTC, joroKr21 commented on core/src/main/scala/cats/sequence/sequence.scala
> +trait GenericSequencerInstanceLowPrio {
This is to ensure we can evolve it later while preserving binary compatibility:
```suggestion
private[sequence] abstract class GenericSequencerInstanceLowPrio {
```

2020-10-22 23:32 UTC, joroKr21 commented on core/src/main/scala/cats/sequence/sequence.scala
> +trait RecordSequencerInstanceLowPrio {
This is to ensure we can evolve it later while preserving binary compatibility:
```suggestion
private[sequence] abstract class RecordSequencerInstanceLowPrio {
```

2020-10-24 08:17 UTC, joroKr21 approved these changes
I made the changes because I'd like to merge and release 2.2.0 this weekend

2020-10-24 08:27 UTC, merged

2021-01-18 17:46 UTC, vinayakpathak commented
Oh, thanks for merging this!

My original motivation for this was to be able to write some appropriate typeclass instances for probability distributions. So you can define a `Rand[T]` class to represent a probability distribution and then you can define a monad instance for `Rand`. Combined with kittens, this gives you a great way to define joint distributions. For example, if you have a `Rand[A]` and a `Rand[B]` you can use the type-level sequence to get a `Rand[A :: B :: HNil]` for free, which is awesome!

However, with the previous code, this would only work if you had an `Applicative` instance for `Rand`. When doing probabilistic modelling, you face situations where all you have is a `Density[A]` (i.e., an unnormalized probability distribution) that simply gives you a `def apply(a: A): Double`. And now you want to be able to define joint _densities_ instead. It is fairly straight-forward to define it mathematically (density over `A and B` is simply the product of density over `A` and density over `B`), but `Density` is not an applicative. This is what prompted me to make this change.

Ideally I would write my tests in terms of `Density` but that's not a data type in cats, so I decided to go with `Semigroup` instead.